export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CANCEL_LOGIN = 'CANCEL_LOGIN';


export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REGISTER_RESPONE = 'REGISTER_FAILED';
export const CANCEL_REGISTER = 'CANCEL_REGISTER';

export const REQUEST_RESET_PASS = 'REQUEST_RESET_PASS';
export const RESPONSE_RESET_PASS = 'RESPONSE_RESET_PASS';

export const REQUEST_ACTIVE_ACCOUNT = 'REQUEST_ACTIVE_ACCOUNT';
export const RESPONSE_ACTIVE_ACCOUNT = 'RESPONSE_ACTIVE_ACCOUNT';
