export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const RESPONSE_REGISTER = 'RESPONSE_REGISTER';

export const REQUEST_RESET_PASS = 'REQUEST_RESET_PASS';
export const RESPONSE_RESET_PASS = 'RESPONSE_RESET_PASS';
