export const REQUEST_DATA = 'REQUEST_DATA';

export const RECEIVE_CATEGORY_BROWSE = 'RECEIVE_CATEGORY';
export const RECEIVE_AUTHOR_BROWSE = 'RECEIVE_AUTHOR';

export const REQUEST_ALL_COURSE = 'REQUEST_ALL_COURSE';
export const RECEIVE_ALL_COURSE = 'RECEIVE_ALL_COURSE';

export const REQUEST_FAILED = 'REQUEST_FAILED';

export const RECEIVE_CATEGORY_DETAILS = 'RECEIVE_CATEGORY_DETAILS';
