export const REQUEST_DATA = 'REQUEST_DATA';

export const REQUEST_FAILED = 'REQUEST_FAILED';

export const FINISH_REQUEST_DATA = 'FINISH_REQUEST_DATA';

export const RECEIVE_CHECK_COURSE = 'RECEIVE_CHECK_COURSE';

export const RECEIVE_LIKE_STATUS = 'RECEIVE_LIKE_STATUS';

export const RECEIVE_COURSE_INFO = 'RECEIVE_COURSE_INFO';

export const RECEIVE_COURSE_SECTION = 'RECEIVE_COURSE_SECTION';

export const RECEIVE_CURRENT_LESSON = 'RECEIVE_CURRENT_LESSON';

export const RECEIVE_LESSON = 'RECEIVE_LESSON';

export const RECEIVE_LESSON_VIDEO = 'RECEIVE_LESSON_VIDEO';

export const RECEIVE_PROCESS = 'RECEIVE_PROCESS';

export const LIKE_COURSE_SUCCESS = 'LIKE_COURSE_SUCCESS';

export const CHANGE_CURRENT_LESSON = 'CHANGE_CURRENT_LESSON';
