export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_TOP_NEW_HOME = 'RECEIVE_TOP_NEW_HOME';
export const RECEIVE_TOP_RATE_HOME = 'RECEIVE_TOP_RATE_HOME';
export const RECEIVE_TOP_SELL_HOME = 'RECEIVE_TOP_SELL_HOME';
export const RECEIVE_RECOMMENDED_HOME = 'RECEIVE_RECOMMENDED_HOME';

export const REQUEST_ALL_COURSE = 'REQUEST_ALL_COURSE';
export const RECEIVE_ALL_COURSE = 'RECEIVE_ALL_COURSE';

export const REQUEST_FAILED = 'REQUEST_FAILED';
