export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const RECEIVE_PROFILE_SUCCESS = 'RECEIVE_SUCCESS';
export const RECEIVE_PROFILE_FAILED = 'RECEIVE_FAILED';

export const REQUEST_UPDATE_PROFILE = 'REQUEST_UPDATE_PROFILE';
export const RECEIVE_RESULT_UPLOAD = 'RECEIVE_RESULT_UPLOAD';

export const REQUEST_UPLOAD_AVATAR = 'REQUEST_UPLOAD_AVATAR';
export const RECEIVE_URL = ' RECEIVE_URL_AVATAR';
