export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';

export const RECEIVE_RECENT_SEARCH = 'RECEIVE_RECENT_SEARCH';
export const CLEAR_RECENT_SEARCH = 'CLEAR_RECENT_SEARCH';
